spring:
  main:
    web-application-type: none
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: /Users/eakhalaivan/Downloads/clinic-website/schema-create.sql
            database:
              action: none
  flyway:
    enabled: true
app:
  datasource:
    growth:
