CREATE TABLE nursing_tasks (
    id BIGSERIAL PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patient_profiles(id) ON DELETE CASCADE,
    encounter_id BIGINT,
    assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    task_type VARCHAR(50) NOT NULL, -- MEDICATION, OBSERVATION, PROCEDURE, OTHER
    description TEXT NOT NULL,
    due_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING', -- PENDING, IN_PROGRESS, COMPLETED, CANCELLED
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    version INT DEFAULT 0
);

CREATE TABLE shift_handovers (
    id BIGSERIAL PRIMARY KEY,
    ward_id BIGINT REFERENCES wards(id) ON DELETE SET NULL,
    outgoing_nurse_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    incoming_nurse_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    handover_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    shift_summary TEXT NOT NULL,
    pending_tasks TEXT,
    critical_patients TEXT,
    status VARCHAR(20) DEFAULT 'DRAFT' -- DRAFT, COMPLETED
);

CREATE TABLE medication_incidents (
    id BIGSERIAL PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patient_profiles(id) ON DELETE CASCADE,
    nurse_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    medication_name VARCHAR(255) NOT NULL,
    incident_type VARCHAR(50) NOT NULL, -- WRONG_DOSE, WRONG_TIME, WRONG_PATIENT, WRONG_MEDICATION, ADVERSE_REACTION, REFUSAL
    incident_time TIMESTAMP WITH TIME ZONE NOT NULL,
    description TEXT NOT NULL,
    action_taken TEXT,
    doctor_notified BOOLEAN DEFAULT FALSE,
    reported_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'OPEN' -- OPEN, UNDER_REVIEW, CLOSED
);
