-- 1. Create fully missing tables
CREATE TABLE IF NOT EXISTS inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    medicine_id BIGINT NOT NULL,
    movement_type VARCHAR(255) NOT NULL,
    notes TEXT,
    quantity INTEGER NOT NULL,
    reference_id VARCHAR(255),
    reference_type VARCHAR(255),
    user_id BIGINT
);

CREATE TABLE IF NOT EXISTS pharmacy_user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

-- 2. Create tables missing on Render (due to baseline skipping V54)
CREATE TABLE IF NOT EXISTS controlled_substance_register (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pharmacy_prescription_id BIGINT NOT NULL,
    medicine_id BIGINT NOT NULL,
    dispensed_quantity INT NOT NULL,
    patient_name VARCHAR(255) NOT NULL,
    doctor_registration_number VARCHAR(255) NOT NULL,
    dispensed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dispensed_by VARCHAR(255) NOT NULL
);

-- 3. Add missing columns across various pharmacy and clinic tables
ALTER TABLE IF EXISTS pharmacy_clearances ADD COLUMN IF NOT EXISTS cleared_by_user_id BIGINT;
ALTER TABLE IF EXISTS pharmacy_prescription_items ADD COLUMN IF NOT EXISTS dispensed_quantity INTEGER;
ALTER TABLE IF EXISTS pharmacy_prescription_items ADD COLUMN IF NOT EXISTS medicine_id BIGINT;
ALTER TABLE IF EXISTS pharmacy_prescription_items ADD COLUMN IF NOT EXISTS prescribed_quantity INTEGER;
ALTER TABLE IF EXISTS pharmacy_prescription_items ADD COLUMN IF NOT EXISTS remaining_quantity INTEGER;
ALTER TABLE IF EXISTS pharmacy_ward_replacement_requests ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE IF EXISTS pharmacy_ward_replacement_returns ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE IF EXISTS prescription_dispensed_items ADD COLUMN IF NOT EXISTS expiry_date DATE;
ALTER TABLE IF EXISTS prescriptions_dispensed ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(100);
ALTER TABLE IF EXISTS prescriptions_dispensed ADD COLUMN IF NOT EXISTS partial_dispense BOOLEAN;
ALTER TABLE IF EXISTS prescriptions_dispensed ADD COLUMN IF NOT EXISTS transaction_reference VARCHAR(100);

-- 4. Align data types and missing unique constraints
ALTER TABLE IF EXISTS lab_test_catalog ALTER COLUMN test_code TYPE VARCHAR(255);
ALTER TABLE IF EXISTS lab_test_requests ALTER COLUMN rejection_notes TYPE VARCHAR(255);
ALTER TABLE IF EXISTS pharmacy_ward_replacement_request_items ALTER COLUMN medicine_name TYPE VARCHAR(255);

ALTER TABLE IF EXISTS attendance DROP CONSTRAINT IF EXISTS UK1pmfeo7o0nrp1m7r33von8gt6;
ALTER TABLE IF EXISTS attendance ADD CONSTRAINT UK1pmfeo7o0nrp1m7r33von8gt6 UNIQUE (employee_id, date);

ALTER TABLE IF EXISTS doctor_performance DROP CONSTRAINT IF EXISTS UKl0f0slbb2o379joaedgrp3plx;
ALTER TABLE IF EXISTS doctor_performance ADD CONSTRAINT UKl0f0slbb2o379joaedgrp3plx UNIQUE (doctor_id, date);
ALTER TABLE IF EXISTS prescription_dispensed_items DROP CONSTRAINT IF EXISTS fk_disp_items_batch CASCADE;
ALTER TABLE IF EXISTS prescription_dispensed_items DROP CONSTRAINT IF EXISTS fkarymp3jegumlgjjcnutpu61g8 CASCADE;

DO $$
DECLARE
    r RECORD;
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'prescription_dispensed_items') THEN
        FOR r IN (
            SELECT constraint_name
            FROM information_schema.key_column_usage
            WHERE table_name = 'prescription_dispensed_items' AND column_name = 'batch_id'
        ) LOOP
            EXECUTE 'ALTER TABLE prescription_dispensed_items DROP CONSTRAINT IF EXISTS ' || quote_ident(r.constraint_name) || ' CASCADE';
        END LOOP;
    END IF;
END $$;

ALTER TABLE IF EXISTS prescription_dispensed_items ALTER COLUMN batch_id TYPE VARCHAR(36);

