-- We assume 'medicines' and `pharmacy_prescriptions` tables already exist from V9.
-- This migration extends the pharmacy module.

CREATE TABLE medicine_batches (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id BIGINT NOT NULL,
    batch_number VARCHAR(100) NOT NULL,
    expiry_date DATE NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(medicine_id, batch_number),
    CONSTRAINT fk_med_batches_medicine FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id) ON DELETE CASCADE
);

CREATE TABLE prescriptions_dispensed (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id BIGINT NOT NULL,
    pharmacist_id BIGINT NOT NULL,
    dispensed_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    notes TEXT
);

CREATE TABLE prescription_dispensed_items (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispensed_id BIGINT NOT NULL,
    medicine_id BIGINT NOT NULL,
    batch_id BIGINT,
    quantity_dispensed INT NOT NULL,
    price_charged DECIMAL(10,2) NOT NULL,
    CONSTRAINT fk_disp_items_dispensed FOREIGN KEY (dispensed_id) REFERENCES prescriptions_dispensed(id) ON DELETE CASCADE,
    CONSTRAINT fk_disp_items_medicine FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id) ON DELETE CASCADE,
    CONSTRAINT fk_disp_items_batch FOREIGN KEY (batch_id) REFERENCES medicine_batches(id) ON DELETE SET NULL
);
