-- V34: Link pharmacy_prescriptions to clinical prescriptions and add medication items
ALTER TABLE pharmacy_prescriptions
    ADD COLUMN clinical_prescription_id BIGINT;

CREATE TABLE IF NOT EXISTS pharmacy_prescription_items (
    id          BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pharmacy_prescription_id BIGINT NOT NULL,
    medication_name VARCHAR(255) NOT NULL,
    dosage       VARCHAR(100),
    frequency    VARCHAR(100),
    duration     VARCHAR(100),
    instructions TEXT,
    created_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rx_items_prescription FOREIGN KEY (pharmacy_prescription_id) REFERENCES pharmacy_prescriptions(id) ON DELETE CASCADE
);

ALTER TABLE pharmacy_prescriptions ADD COLUMN dispensed_at TIMESTAMP(6);
ALTER TABLE pharmacy_prescriptions ADD COLUMN dispensed_by VARCHAR(255);
