CREATE TABLE pharmacy_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP(6)
);
CREATE INDEX idx_pharmacy_outbox_status ON pharmacy_outbox_events(status);
