-- MySQL schema (converted from pg_dump)


--
-- Name: pharmacy_activity_logs; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_activity_logs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    action VARCHAR(255),
    created_at TIMESTAMP(6),
    description VARCHAR(500),
    ip_address VARCHAR(255),
    module VARCHAR(255),
    user_id bigint,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_barcode_scan_logs; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_barcode_scan_logs (
    scan_id VARCHAR(36) NOT NULL,
    barcode_value VARCHAR(200) NOT NULL,
    resolved_batch_id VARCHAR(255),
    resolved_medicine_id bigint,
    scan_module VARCHAR(60),
    scan_result VARCHAR(30) NOT NULL,
    scan_type VARCHAR(30) NOT NULL,
    scanned_at TIMESTAMP(6),
    scanned_by bigint NOT NULL,
    PRIMARY KEY (scan_id)
);


--
-- Name: pharmacy_batch_return_to_supplier; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_batch_return_to_supplier (
    return_id VARCHAR(36) NOT NULL,
    actual_credit_value DECIMAL(38,2),
    batch_id VARCHAR(36) NOT NULL,
    courier_details text,
    created_at TIMESTAMP(6),
    credit_note_date date,
    credit_note_number VARCHAR(50),
    dispatch_date date,
    expected_credit_value DECIMAL(38,2),
    initiated_by bigint NOT NULL,
    return_reason VARCHAR(30) NOT NULL,
    return_status VARCHAR(30),
    returned_quantity integer NOT NULL,
    updated_at TIMESTAMP(6),
    medicine_id bigint NOT NULL,
    supplier_id bigint NOT NULL,
    PRIMARY KEY (return_id)
);


--
-- Name: pharmacy_bill_cancellation_requests; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_bill_cancellation_requests (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    bill_id bigint NOT NULL,
    reason VARCHAR(255) NOT NULL,
    requested_at TIMESTAMP(6) NOT NULL,
    requested_by VARCHAR(255) NOT NULL,
    reviewed_at TIMESTAMP(6),
    reviewed_by VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_credit_bills; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_credit_bills (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    balance_amount DECIMAL(38,2) NOT NULL,
    paid_amount DECIMAL(38,2) NOT NULL,
    status VARCHAR(255),
    total_amount DECIMAL(38,2) NOT NULL,
    bill_id bigint NOT NULL,
    CONSTRAINT pharmacy_credit_bills_status_check CHECK (status IN ('PAID', 'PARTIAL', 'UNPAID', 'CANCELLED')),
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_doctors; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_doctors (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    clinic_address text,
    contact_number VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    registration_number VARCHAR(255),
    specialization VARCHAR(255),
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_drug_interaction_checks; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_drug_interaction_checks (
    check_id VARCHAR(36) NOT NULL,
    bill_id bigint,
    checked_at TIMESTAMP(6),
    medicine_a_name VARCHAR(150),
    medicine_b_name VARCHAR(150),
    was_overridden boolean,
    override_reason text,
    patient_id bigint,
    patient_name VARCHAR(100),
    severity VARCHAR(20) NOT NULL,
    interaction_id VARCHAR(36),
    medicine_a_id bigint NOT NULL,
    medicine_b_id bigint NOT NULL,
    override_by bigint,
    PRIMARY KEY (check_id)
);


--
-- Name: pharmacy_drug_interactions; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_drug_interactions (
    interaction_id VARCHAR(36) NOT NULL,
    is_active boolean,
    clinical_consequence text NOT NULL,
    created_at TIMESTAMP(6),
    created_by VARCHAR(36),
    documentation_level VARCHAR(20) NOT NULL,
    interaction_mechanism text,
    interaction_type VARCHAR(100),
    medicine_a_name VARCHAR(150) NOT NULL,
    medicine_b_name VARCHAR(150) NOT NULL,
    onset VARCHAR(50),
    recommended_action text NOT NULL,
    severity VARCHAR(20) NOT NULL,
    updated_at TIMESTAMP(6),
    medicine_a_id bigint NOT NULL,
    medicine_b_id bigint NOT NULL,
    PRIMARY KEY (interaction_id)
);


--
-- Name: pharmacy_goods_receipt_note_items; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_goods_receipt_note_items (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    batch_number VARCHAR(255),
    expiry_date date,
    manufacturing_date date,
    mrp DECIMAL(38,2),
    ordered_quantity integer,
    po_item_id bigint,
    purchase_rate DECIMAL(38,2),
    received_quantity integer,
    rejected_quantity integer,
    rejection_reason VARCHAR(255),
    grn_id bigint NOT NULL,
    medicine_id bigint NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_goods_receipt_notes; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_goods_receipt_notes (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    delivery_challan_number VARCHAR(255),
    grn_number VARCHAR(255) NOT NULL,
    invoice_date date,
    received_by VARCHAR(255),
    received_date TIMESTAMP(6),
    status VARCHAR(255) NOT NULL,
    supplier_invoice_number VARCHAR(255),
    vehicle_number VARCHAR(255),
    purchase_order_id VARCHAR(36) NOT NULL,
    supplier_id bigint NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_insurance_claim_line_items; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_insurance_claim_line_items (
    claim_line_id VARCHAR(36) NOT NULL,
    bill_line_item_id bigint,
    coverage_percentage DECIMAL(38,2),
    is_covered boolean NOT NULL,
    covered_amount DECIMAL(38,2),
    created_at TIMESTAMP(6),
    line_total DECIMAL(38,2) NOT NULL,
    medicine_name VARCHAR(150) NOT NULL,
    non_covered_amount DECIMAL(38,2),
    non_covered_reason VARCHAR(150),
    quantity integer NOT NULL,
    unit_price DECIMAL(38,2) NOT NULL,
    claim_id VARCHAR(36) NOT NULL,
    medicine_id bigint NOT NULL,
    PRIMARY KEY (claim_line_id)
);


--
-- Name: pharmacy_insurance_claims; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_insurance_claims (
    claim_id VARCHAR(36) NOT NULL,
    approval_date date,
    approved_amount DECIMAL(38,2),
    claim_date date NOT NULL,
    claim_document_url text,
    claim_number VARCHAR(30) NOT NULL,
    claim_status VARCHAR(30),
    claimed_amount DECIMAL(38,2) NOT NULL,
    covered_amount DECIMAL(38,2) NOT NULL,
    created_at TIMESTAMP(6),
    created_by bigint NOT NULL,
    insurance_policy_number VARCHAR(60) NOT NULL,
    non_covered_amount DECIMAL(38,2) NOT NULL,
    patient_name VARCHAR(100) NOT NULL,
    patient_uhid VARCHAR(30),
    rejected_amount DECIMAL(38,2),
    rejection_reason text,
    settlement_date date,
    settlement_reference VARCHAR(60),
    submission_date date,
    total_bill_amount DECIMAL(38,2) NOT NULL,
    tpa_name VARCHAR(100),
    updated_at TIMESTAMP(6),
    bill_id bigint,
    patient_id bigint,
    insurance_provider_id VARCHAR(36) NOT NULL,
    PRIMARY KEY (claim_id)
);


--
-- Name: pharmacy_insurance_medicine_coverage; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_insurance_medicine_coverage (
    coverage_id VARCHAR(36) NOT NULL,
    coverage_notes text,
    coverage_percentage DECIMAL(38,2),
    is_covered boolean,
    created_at TIMESTAMP(6),
    effective_from date NOT NULL,
    effective_to date,
    max_coverage_amount DECIMAL(38,2),
    medicine_name VARCHAR(150) NOT NULL,
    medicine_id bigint NOT NULL,
    provider_id VARCHAR(36) NOT NULL,
    PRIMARY KEY (coverage_id)
);


--
-- Name: pharmacy_insurance_providers; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_insurance_providers (
    provider_id VARCHAR(36) NOT NULL,
    is_active boolean,
    address text,
    claim_portal_url VARCHAR(200),
    claim_submission_mode VARCHAR(30) NOT NULL,
    contact_person VARCHAR(100),
    coverage_policy text,
    created_at TIMESTAMP(6),
    email VARCHAR(100),
    mobile VARCHAR(15),
    provider_code VARCHAR(20) NOT NULL,
    provider_name VARCHAR(150) NOT NULL,
    provider_type VARCHAR(30) NOT NULL,
    turnaround_days integer,
    PRIMARY KEY (provider_id)
);


--
-- Name: pharmacy_medicine_return_items; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_medicine_return_items (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    bill_item_id bigint,
    quantity integer NOT NULL,
    return_amount DECIMAL(38,2) NOT NULL,
    return_id bigint NOT NULL,
    stock_id bigint NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_medicine_returns; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_medicine_returns (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    reason VARCHAR(255),
    return_date TIMESTAMP(6) NOT NULL,
    status VARCHAR(255),
    total_return_amount DECIMAL(38,2) NOT NULL,
    original_bill_id bigint NOT NULL,
    CONSTRAINT pharmacy_medicine_returns_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_medicine_stocks; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_medicine_stocks (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    batch_number VARCHAR(255) NOT NULL,
    branch_id bigint NOT NULL,
    date_of_entry date,
    expiry_date date NOT NULL,
    grn_reference VARCHAR(255),
    manufacturing_date date,
    purchase_rate DECIMAL(38,2) NOT NULL,
    quantity_available integer NOT NULL,
    quantity_received integer NOT NULL,
    selling_rate DECIMAL(38,2) NOT NULL,
    medicine_id bigint NOT NULL,
    supplier_id bigint,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_medicines; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_medicines (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    barcode VARCHAR(255),
    category VARCHAR(255),
    drug_class VARCHAR(255),
    generic_name VARCHAR(255),
    hsn_code VARCHAR(255),
    manufacturer VARCHAR(255),
    medicine_code VARCHAR(255),
    mrp DECIMAL(38,2),
    name VARCHAR(255) NOT NULL,
    pack_size VARCHAR(255),
    product_type VARCHAR(50),
    purchase_price DECIMAL(38,2),
    reorder_level integer,
    reorder_quantity integer,
    sale_price DECIMAL(38,2),
    schedule VARCHAR(255),
    storage_conditions VARCHAR(255),
    substitutes VARCHAR(255),
    supplier_vendor VARCHAR(255),
    tax_percentage DECIMAL(38,2) NOT NULL,
    unit VARCHAR(255),
    units_per_pack integer DEFAULT 1,
    supplier_id bigint,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_narcotic_monthly_reconciliation; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_narcotic_monthly_reconciliation (
    reconciliation_id VARCHAR(36) NOT NULL,
    approved_at TIMESTAMP(6),
    approved_by bigint,
    is_balanced boolean,
    closing_stock_calculated integer NOT NULL,
    closing_stock_physical integer,
    medicine_name VARCHAR(150) NOT NULL,
    opening_stock integer NOT NULL,
    reconciled_at TIMESTAMP(6),
    reconciled_by bigint,
    reconciliation_month integer NOT NULL,
    reconciliation_year integer NOT NULL,
    remarks VARCHAR(1000),
    total_dispensed integer NOT NULL,
    total_received integer,
    total_returned integer,
    total_written_off integer,
    variance integer,
    medicine_id bigint NOT NULL,
    PRIMARY KEY (reconciliation_id)
);


--
-- Name: pharmacy_narcotic_register; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_narcotic_register (
    entry_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    bed_number VARCHAR(255),
    closing_balance integer NOT NULL,
    digital_acknowledgment_timestamp TIMESTAMP(6),
    discrepancy_flag boolean,
    dispensing_pharmacist_id bigint,
    doctor_name VARCHAR(255),
    doctor_registration_number VARCHAR(255),
    entry_date TIMESTAMP(6),
    opening_balance integer NOT NULL,
    patient_age integer,
    patient_full_name VARCHAR(255) NOT NULL,
    patient_gender VARCHAR(255),
    prescription_date date,
    prescription_number VARCHAR(255),
    quantity_dispensed integer NOT NULL,
    quantity_prescribed integer NOT NULL,
    remarks VARCHAR(1000),
    serial_number VARCHAR(255) NOT NULL,
    ward_name VARCHAR(255),
    batch_id bigint NOT NULL,
    medicine_id bigint NOT NULL,
    patient_id bigint,
    PRIMARY KEY (entry_id)
);


--


--
-- Name: pharmacy_patients; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_patients (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    address VARCHAR(255),
    branch_id bigint NOT NULL,
    delivery_address text,
    dob date,
    gender VARCHAR(255),
    insurance_id VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    preferred_delivery boolean,
    uhid VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_payment_transactions; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_payment_transactions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    amount DECIMAL(38,2) NOT NULL,
    payment_date TIMESTAMP(6) NOT NULL,
    payment_mode VARCHAR(255) NOT NULL,
    transaction_reference VARCHAR(255),
    credit_bill_id bigint NOT NULL,
    CONSTRAINT pharmacy_payment_transactions_payment_mode_check CHECK (payment_mode IN ('CASH', 'CARD', 'UPI', 'ADVANCE', 'CREDIT')),
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_pharmacy_advances; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_pharmacy_advances (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    advance_date TIMESTAMP(6) NOT NULL,
    amount DECIMAL(38,2) NOT NULL,
    balance_amount DECIMAL(38,2) NOT NULL,
    branch_id bigint NOT NULL,
    patient_id bigint,
    patient_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_po_line_items; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_po_line_items (
    line_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP(6),
    gst_percentage DECIMAL(38,2) NOT NULL,
    hsn_code VARCHAR(10),
    line_gst DECIMAL(38,2) NOT NULL,
    line_subtotal DECIMAL(38,2) NOT NULL,
    line_total DECIMAL(38,2) NOT NULL,
    medicine_code VARCHAR(20),
    medicine_name VARCHAR(150) NOT NULL,
    ordered_quantity integer NOT NULL,
    pending_quantity integer,
    received_quantity integer,
    unit_price DECIMAL(38,2) NOT NULL,
    medicine_id bigint NOT NULL,
    po_id VARCHAR(36) NOT NULL,
    PRIMARY KEY (line_id)
);


--
-- Name: pharmacy_prescriptions; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_prescriptions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    doctor_name VARCHAR(255),
    patient_name VARCHAR(255) NOT NULL,
    prescription_date TIMESTAMP(6) NOT NULL,
    status VARCHAR(255) NOT NULL,
    verification_status VARCHAR(255) NOT NULL,
    verified_at TIMESTAMP(6),
    verified_by VARCHAR(255),
    doctor_id bigint,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_purchase_order_items; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_purchase_order_items (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    estimated_unit_price DECIMAL(38,2),
    gst_percentage double precision,
    hsn_code VARCHAR(255),
    last_purchase_price DECIMAL(38,2),
    line_total DECIMAL(38,2),
    negotiated_price DECIMAL(38,2),
    quantity integer NOT NULL,
    medicine_id bigint NOT NULL,
    purchase_order_id VARCHAR(36) NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_purchase_orders; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_purchase_orders (
    po_id VARCHAR(36) NOT NULL,
    approved_at TIMESTAMP(6),
    approved_by bigint,
    is_auto_generated boolean,
    auto_generated_reason text,
    billing_address text,
    branch_id bigint NOT NULL,
    cancellation_reason text,
    cancelled_by bigint,
    created_at TIMESTAMP(6),
    created_by bigint NOT NULL,
    delivery_address text,
    expected_delivery_date date NOT NULL,
    gst_amount DECIMAL(38,2),
    internal_remarks text,
    po_date date NOT NULL,
    po_number VARCHAR(30) NOT NULL,
    priority VARCHAR(20),
    sent_at TIMESTAMP(6),
    status VARCHAR(30),
    submitted_at TIMESTAMP(6),
    submitted_by bigint,
    subtotal DECIMAL(38,2),
    supplier_gstin VARCHAR(15),
    supplier_name VARCHAR(150) NOT NULL,
    terms_and_conditions text,
    total_value DECIMAL(38,2),
    updated_at TIMESTAMP(6),
    supplier_id bigint NOT NULL,
    PRIMARY KEY (po_id)
);


--
-- Name: pharmacy_report_schedules; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_report_schedules (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    is_active boolean,
    channels VARCHAR(255),
    cron_expression VARCHAR(255),
    delivery_time VARCHAR(255),
    email_recipients VARCHAR(1000),
    file_formats VARCHAR(255),
    frequency VARCHAR(255) NOT NULL,
    last_sent_at TIMESTAMP(6),
    last_sent_error VARCHAR(500),
    last_sent_status VARCHAR(255),
    report_category VARCHAR(255),
    report_params VARCHAR(2000),
    report_type VARCHAR(255) NOT NULL,
    schedule_name VARCHAR(255) NOT NULL,
    whatsapp_numbers VARCHAR(500),
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_return_to_supplier_items; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_return_to_supplier_items (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    batch_number VARCHAR(255),
    line_total DECIMAL(38,2),
    return_quantity integer,
    unit_price DECIMAL(38,2),
    medicine_id bigint NOT NULL,
    return_id bigint NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_return_to_suppliers; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_return_to_suppliers (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    actual_credit_value DECIMAL(38,2),
    credit_note_number VARCHAR(255),
    expected_credit_value DECIMAL(38,2),
    reason VARCHAR(255),
    return_number VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    transport_details VARCHAR(500),
    grn_id bigint NOT NULL,
    supplier_id bigint NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_roles; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_roles (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    color VARCHAR(255) NOT NULL,
    is_system_default boolean,
    name VARCHAR(255) NOT NULL,
    permissions_json text,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_sales_bills; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_sales_bills (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    advance_adjusted DECIMAL(38,2),
    amount_due DECIMAL(38,2),
    balance_amount DECIMAL(38,2),
    bill_number VARCHAR(255) NOT NULL,
    bill_type VARCHAR(255) NOT NULL,
    bill_date TIMESTAMP(6) NOT NULL,
    branch_id bigint NOT NULL,
    discount_amount DECIMAL(38,2),
    doctor_name VARCHAR(255),
    net_amount DECIMAL(38,2) NOT NULL,
    paid_amount DECIMAL(38,2),
    patient_name VARCHAR(255),
    payment_mode VARCHAR(255),
    payment_status VARCHAR(255),
    bill_status VARCHAR(255) NOT NULL,
    sub_total DECIMAL(38,2) NOT NULL,
    tax_amount DECIMAL(38,2),
    total_gst_amount DECIMAL(38,2),
    doctor_id bigint,
    patient_id bigint,
    CONSTRAINT pharmacy_sales_bills_payment_status_check CHECK (payment_status IN ('PAID', 'PARTIAL', 'UNPAID', 'CANCELLED')),
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_sales_line_items; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_sales_line_items (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    discount_amount DECIMAL(38,2),
    net_amount DECIMAL(38,2) NOT NULL,
    quantity integer NOT NULL,
    tax_amount DECIMAL(38,2),
    unit_price DECIMAL(38,2) NOT NULL,
    bill_id bigint NOT NULL,
    stock_id bigint NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_stock_adjustments; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_stock_adjustments (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    adjusted_quantity integer NOT NULL,
    adjustment_type VARCHAR(255) NOT NULL,
    batch_id bigint NOT NULL,
    reason VARCHAR(255) NOT NULL,
    remarks VARCHAR(255),
    "timestamp" TIMESTAMP(6) NOT NULL,
    adjusted_by_user_id bigint NOT NULL,
    medicine_id bigint NOT NULL,
    medicine_stock_id bigint NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_stock_alerts; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_stock_alerts (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    alert_type VARCHAR(255),
    created_at TIMESTAMP(6),
    sent_to VARCHAR(255),
    medicine_id bigint NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_stock_batches; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_stock_batches (
    batch_id VARCHAR(36) NOT NULL,
    batch_number VARCHAR(60) NOT NULL,
    created_at TIMESTAMP(6),
    created_by VARCHAR(36),
    drug_class VARCHAR(60),
    is_expired boolean,
    expiry_date date NOT NULL,
    fefo_priority integer,
    generic_name VARCHAR(150),
    grn_id VARCHAR(36),
    grn_number VARCHAR(30),
    manufacturing_date date NOT NULL,
    medicine_name VARCHAR(150) NOT NULL,
    mrp DECIMAL(38,2) NOT NULL,
    purchase_price DECIMAL(38,2) NOT NULL,
    quantity_available integer NOT NULL,
    quantity_received integer NOT NULL,
    quantity_reserved integer,
    quarantine_reason text,
    is_quarantined boolean,
    storage_location VARCHAR(60),
    supplier_name VARCHAR(150),
    updated_at TIMESTAMP(6),
    medicine_id bigint NOT NULL,
    supplier_id bigint,
    PRIMARY KEY (batch_id)
);


--
-- Name: pharmacy_storage_units; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_storage_units (
    unit_id VARCHAR(36) NOT NULL,
    is_active boolean,
    assigned_medicines text,
    iot_device_id VARCHAR(60),
    is_iot_enabled boolean,
    location VARCHAR(100),
    max_threshold DECIMAL(38,2) NOT NULL,
    min_threshold DECIMAL(38,2) NOT NULL,
    unit_name VARCHAR(100) NOT NULL,
    unit_type VARCHAR(30) NOT NULL,
    PRIMARY KEY (unit_id)
);


--
-- Name: pharmacy_supplier_invoice_items; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_supplier_invoice_items (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    billed_price DECIMAL(38,2),
    billed_quantity integer,
    discrepancy_severity VARCHAR(255),
    discrepancy_type VARCHAR(255),
    grn_item_id bigint,
    gst_percentage double precision,
    line_total DECIMAL(38,2),
    po_item_id bigint,
    medicine_id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_supplier_invoices; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_supplier_invoices (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    due_date date,
    gstin_on_invoice VARCHAR(255),
    invoice_date date,
    invoice_number VARCHAR(255) NOT NULL,
    match_notes VARCHAR(1000),
    status VARCHAR(255) NOT NULL,
    subtotal DECIMAL(38,2),
    tax_amount DECIMAL(38,2),
    total_amount DECIMAL(38,2),
    grn_id bigint,
    purchase_order_id VARCHAR(36),
    supplier_id bigint NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_supplier_performance; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_supplier_performance (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    credit_note_response_days double precision,
    invoice_accuracy_rate double precision,
    manual_notes VARCHAR(1000),
    on_time_delivery_rate double precision,
    order_fill_rate double precision,
    overall_score double precision,
    period_end date,
    period_start date,
    price_variance_rate double precision,
    quality_rejection_rate double precision,
    return_rate double precision,
    supplier_id bigint NOT NULL,
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_suppliers; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_suppliers (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    account_number VARCHAR(255),
    address VARCHAR(255),
    alternate_phone VARCHAR(255),
    average_lead_time integer,
    bank_name VARCHAR(255),
    branch VARCHAR(255),
    city VARCHAR(255),
    contact VARCHAR(255),
    contact_person_name VARCHAR(255),
    country VARCHAR(255),
    credit_limit double precision,
    designation VARCHAR(255),
    drug_license_expiry date,
    drug_license_number VARCHAR(255),
    email_address VARCHAR(255),
    gstin VARCHAR(255),
    ifsc_code VARCHAR(255),
    mobile_number VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    notes VARCHAR(1000),
    pan_number VARCHAR(255),
    payment_terms VARCHAR(255),
    pincode VARCHAR(255),
    preferred_delivery_days VARCHAR(255),
    state VARCHAR(255),
    status VARCHAR(255),
    supplier_code VARCHAR(255) NOT NULL,
    supplier_type VARCHAR(255),
    PRIMARY KEY (id)
);


--


--
-- Name: pharmacy_temperature_logs; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_temperature_logs (
    log_id VARCHAR(36) NOT NULL,
    is_breach boolean,
    breach_notes text,
    breach_severity VARCHAR(20),
    corrective_action text,
    corrective_action_at TIMESTAMP(6),
    corrective_action_by bigint,
    log_type VARCHAR(30),
    max_threshold DECIMAL(38,2) NOT NULL,
    medicines_affected text,
    min_threshold DECIMAL(38,2) NOT NULL,
    recorded_at TIMESTAMP(6),
    recorded_by bigint NOT NULL,
    recorded_temperature DECIMAL(38,2) NOT NULL,
    unit_name VARCHAR(100) NOT NULL,
    unit_type VARCHAR(30),
    unit_id VARCHAR(36) NOT NULL,
    PRIMARY KEY (log_id)
);


--
-- Name: pharmacy_users; Type: TABLE; Schema: public; Owner: clinic_admin
--

CREATE TABLE IF NOT EXISTS pharmacy_users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    is_deleted boolean NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    branch VARCHAR(255),
    email VARCHAR(255),
    employee_id VARCHAR(255),
    last_login TIMESTAMP(6),
    last_logout TIMESTAMP(6),
    role VARCHAR(255),
    must_change_password boolean NOT NULL,
    name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    profile_photo_url text,
    shift VARCHAR(255),
    status VARCHAR(255),
    username VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);


--



































































































































--
-- Name: pharmacy_insurance_providers uk54g30cflwj60uh76af1eurmi; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_insurance_providers
    ADD CONSTRAINT uk54g30cflwj60uh76af1eurmi UNIQUE (provider_code);


--
-- Name: pharmacy_goods_receipt_notes ukaglqfssxdjdjgb4086jbl1wn6; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_goods_receipt_notes
    ADD CONSTRAINT ukaglqfssxdjdjgb4086jbl1wn6 UNIQUE (grn_number);


--
-- Name: pharmacy_users ukbkgbfmmxhdvfeknago3kq3f1b; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_users
    ADD CONSTRAINT ukbkgbfmmxhdvfeknago3kq3f1b UNIQUE (username);


--
-- Name: pharmacy_credit_bills ukdufix6l3w4duwr1vdo49q4sv2; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_credit_bills
    ADD CONSTRAINT ukdufix6l3w4duwr1vdo49q4sv2 UNIQUE (bill_id);


--
-- Name: pharmacy_narcotic_register ukehoobtsi2nb81i39jcpyagtea; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_narcotic_register
    ADD CONSTRAINT ukehoobtsi2nb81i39jcpyagtea UNIQUE (serial_number);


--
-- Name: pharmacy_return_to_suppliers ukf5lhtvkfkivvjjvglkfy61xpg; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_return_to_suppliers
    ADD CONSTRAINT ukf5lhtvkfkivvjjvglkfy61xpg UNIQUE (return_number);


--
-- Name: pharmacy_sales_bills ukhlrgy0u1u5nie0njse08q411n; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_sales_bills
    ADD CONSTRAINT ukhlrgy0u1u5nie0njse08q411n UNIQUE (bill_number);


--
-- Name: pharmacy_medicines ukjfojt0pgu45ifmo71h1x4ggk4; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_medicines
    ADD CONSTRAINT ukjfojt0pgu45ifmo71h1x4ggk4 UNIQUE (barcode);


--
-- Name: pharmacy_suppliers ukjgud2w1cbi4aounwex420arui; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_suppliers
    ADD CONSTRAINT ukjgud2w1cbi4aounwex420arui UNIQUE (supplier_code);


--
-- Name: pharmacy_patients uklpl0h77n5iglxnnu3nof1l762; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_patients
    ADD CONSTRAINT uklpl0h77n5iglxnnu3nof1l762 UNIQUE (uhid);


--
-- Name: pharmacy_insurance_claims ukp2cibca7mfaxavuwsu6cqkcap; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_insurance_claims
    ADD CONSTRAINT ukp2cibca7mfaxavuwsu6cqkcap UNIQUE (claim_number);


--
-- Name: pharmacy_purchase_orders ukp7fxye01y6trdlbqioqag2ctg; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_purchase_orders
    ADD CONSTRAINT ukp7fxye01y6trdlbqioqag2ctg UNIQUE (po_number);


--
-- Name: pharmacy_medicines ukqe17pouig29pyoigbuf3qn3ea; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_medicines
    ADD CONSTRAINT ukqe17pouig29pyoigbuf3qn3ea UNIQUE (medicine_code);


--
-- Name: pharmacy_roles ukqes979ljqhntv6w0iqykh7rbw; Type: CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_roles
    ADD CONSTRAINT ukqes979ljqhntv6w0iqykh7rbw UNIQUE (name);


--
-- Name: pharmacy_medicine_returns fk180j07qcre650oih6f62x21n8; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_medicine_returns
    ADD CONSTRAINT fk180j07qcre650oih6f62x21n8 FOREIGN KEY (original_bill_id) REFERENCES pharmacy_sales_bills(id);


--
-- Name: pharmacy_stock_adjustments fk1olk7e8gwy7h3t8sscluq33xf; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_stock_adjustments
    ADD CONSTRAINT fk1olk7e8gwy7h3t8sscluq33xf FOREIGN KEY (medicine_stock_id) REFERENCES pharmacy_medicine_stocks(id);


--
-- Name: pharmacy_insurance_claim_line_items fk2blyrhugiyq861eynyelpoo8o; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_insurance_claim_line_items
    ADD CONSTRAINT fk2blyrhugiyq861eynyelpoo8o FOREIGN KEY (claim_id) REFERENCES pharmacy_insurance_claims(claim_id);


--
-- Name: pharmacy_sales_bills fk2celsye3umd072c7lwevfwo0h; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_sales_bills
    ADD CONSTRAINT fk2celsye3umd072c7lwevfwo0h FOREIGN KEY (patient_id) REFERENCES pharmacy_patients(id);


--
-- Name: pharmacy_insurance_claims fk33r979w9agj103cwqkd22500r; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_insurance_claims
    ADD CONSTRAINT fk33r979w9agj103cwqkd22500r FOREIGN KEY (bill_id) REFERENCES pharmacy_sales_bills(id);


--
-- Name: pharmacy_narcotic_monthly_reconciliation fk368nn4qit24t1j2joiitneyhe; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_narcotic_monthly_reconciliation
    ADD CONSTRAINT fk368nn4qit24t1j2joiitneyhe FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_goods_receipt_note_items fk38k64hk4bmgxkx0l5qlewh488; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_goods_receipt_note_items
    ADD CONSTRAINT fk38k64hk4bmgxkx0l5qlewh488 FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_drug_interaction_checks fk3uwydpp6lhdemfjm8drrw7d0m; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_drug_interaction_checks
    ADD CONSTRAINT fk3uwydpp6lhdemfjm8drrw7d0m FOREIGN KEY (override_by) REFERENCES pharmacy_users(id);


--
-- Name: pharmacy_purchase_order_items fk4dcp1c3a9hxl4hkmvjvl5vbma; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_purchase_order_items
    ADD CONSTRAINT fk4dcp1c3a9hxl4hkmvjvl5vbma FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_supplier_invoices fk4inl2itx4mi4mj3t5po1riv2e; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_supplier_invoices
    ADD CONSTRAINT fk4inl2itx4mi4mj3t5po1riv2e FOREIGN KEY (purchase_order_id) REFERENCES pharmacy_purchase_orders(po_id);


--
-- Name: pharmacy_supplier_invoice_items fk4ljsl1gcj7fip3ni285o8943i; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_supplier_invoice_items
    ADD CONSTRAINT fk4ljsl1gcj7fip3ni285o8943i FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_stock_adjustments fk5t5ddqidfj57t5wabvbbfl56x; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_stock_adjustments
    ADD CONSTRAINT fk5t5ddqidfj57t5wabvbbfl56x FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_drug_interaction_checks fk63m20pamhvx1ghb2cmpt8uftl; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_drug_interaction_checks
    ADD CONSTRAINT fk63m20pamhvx1ghb2cmpt8uftl FOREIGN KEY (interaction_id) REFERENCES pharmacy_drug_interactions(interaction_id);


--
-- Name: pharmacy_supplier_invoice_items fk66s0muccc3h3v2mtet6m6lpqh; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_supplier_invoice_items
    ADD CONSTRAINT fk66s0muccc3h3v2mtet6m6lpqh FOREIGN KEY (invoice_id) REFERENCES pharmacy_supplier_invoices(id);


--
-- Name: pharmacy_insurance_claims fk6waor3tlnhh9f9uv6mvc4wme1; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_insurance_claims
    ADD CONSTRAINT fk6waor3tlnhh9f9uv6mvc4wme1 FOREIGN KEY (insurance_provider_id) REFERENCES pharmacy_insurance_providers(provider_id);


--
-- Name: pharmacy_insurance_medicine_coverage fk75290hgo6fk4kyu61mv874biv; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_insurance_medicine_coverage
    ADD CONSTRAINT fk75290hgo6fk4kyu61mv874biv FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_return_to_supplier_items fk8lgjhdiau03uh9ema06n03q32; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_return_to_supplier_items
    ADD CONSTRAINT fk8lgjhdiau03uh9ema06n03q32 FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_medicine_return_items fk8w0e2vprnqkqs0snsfhx2a18x; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_medicine_return_items
    ADD CONSTRAINT fk8w0e2vprnqkqs0snsfhx2a18x FOREIGN KEY (stock_id) REFERENCES pharmacy_medicine_stocks(id);


--
-- Name: pharmacy_narcotic_register fk906yi5rndy2lo77pcaqcnw3i5; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_narcotic_register
    ADD CONSTRAINT fk906yi5rndy2lo77pcaqcnw3i5 FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_prescriptions fkahbdygo9uc24edp4au4i62no9; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_prescriptions
    ADD CONSTRAINT fkahbdygo9uc24edp4au4i62no9 FOREIGN KEY (doctor_id) REFERENCES pharmacy_doctors(id);


--
-- Name: pharmacy_purchase_orders fkap6svvnei2jcttbpm7joclk50; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_purchase_orders
    ADD CONSTRAINT fkap6svvnei2jcttbpm7joclk50 FOREIGN KEY (supplier_id) REFERENCES pharmacy_suppliers(id);


--
-- Name: pharmacy_medicine_stocks fkb1tqjo6sgpje6u0x9u2w92het; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_medicine_stocks
    ADD CONSTRAINT fkb1tqjo6sgpje6u0x9u2w92het FOREIGN KEY (supplier_id) REFERENCES pharmacy_suppliers(id);


--
-- Name: pharmacy_drug_interaction_checks fkceyaihpw9wsf8o37bpn3ebngr; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_drug_interaction_checks
    ADD CONSTRAINT fkceyaihpw9wsf8o37bpn3ebngr FOREIGN KEY (medicine_b_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_medicine_return_items fkduhdyx04awdh8olkyswxrjy95; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_medicine_return_items
    ADD CONSTRAINT fkduhdyx04awdh8olkyswxrjy95 FOREIGN KEY (return_id) REFERENCES pharmacy_medicine_returns(id);


--
-- Name: pharmacy_payment_transactions fkgvx2au3d7v9fcxr9pq1o5l7mp; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_payment_transactions
    ADD CONSTRAINT fkgvx2au3d7v9fcxr9pq1o5l7mp FOREIGN KEY (credit_bill_id) REFERENCES pharmacy_credit_bills(id);


--
-- Name: pharmacy_medicine_stocks fkhs6x9gy1ndpeu5dmnaa7wblnc; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_medicine_stocks
    ADD CONSTRAINT fkhs6x9gy1ndpeu5dmnaa7wblnc FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_batch_return_to_supplier fki1m0we6bdfbv38da1sca4hk1e; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_batch_return_to_supplier
    ADD CONSTRAINT fki1m0we6bdfbv38da1sca4hk1e FOREIGN KEY (supplier_id) REFERENCES pharmacy_suppliers(id);


--
-- Name: pharmacy_insurance_claim_line_items fki3hr86yob2jhot3cphv339k1o; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_insurance_claim_line_items
    ADD CONSTRAINT fki3hr86yob2jhot3cphv339k1o FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_narcotic_register fki7bdv4nv9i56rprrkoqomvlpk; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_narcotic_register
    ADD CONSTRAINT fki7bdv4nv9i56rprrkoqomvlpk FOREIGN KEY (patient_id) REFERENCES pharmacy_patients(id);


--
-- Name: pharmacy_supplier_performance fkip2eyr6ultts7mci7upb6jmd8; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_supplier_performance
    ADD CONSTRAINT fkip2eyr6ultts7mci7upb6jmd8 FOREIGN KEY (supplier_id) REFERENCES pharmacy_suppliers(id);


--
-- Name: pharmacy_drug_interactions fkj3c0w8qifxmsex1nhdme3j90s; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_drug_interactions
    ADD CONSTRAINT fkj3c0w8qifxmsex1nhdme3j90s FOREIGN KEY (medicine_b_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_credit_bills fkj56ndflnm4cu7u895dern766d; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_credit_bills
    ADD CONSTRAINT fkj56ndflnm4cu7u895dern766d FOREIGN KEY (bill_id) REFERENCES pharmacy_sales_bills(id);


--
-- Name: pharmacy_batch_return_to_supplier fkj7ael6i00uvsoydaf7mh9jd3; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_batch_return_to_supplier
    ADD CONSTRAINT fkj7ael6i00uvsoydaf7mh9jd3 FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_narcotic_register fkjk2v7iqhhwurro2nulpfmb0vq; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_narcotic_register
    ADD CONSTRAINT fkjk2v7iqhhwurro2nulpfmb0vq FOREIGN KEY (batch_id) REFERENCES pharmacy_medicine_stocks(id);


--
-- Name: pharmacy_goods_receipt_note_items fkjmhbbovlcc5hqvosrqkpmp8ns; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_goods_receipt_note_items
    ADD CONSTRAINT fkjmhbbovlcc5hqvosrqkpmp8ns FOREIGN KEY (grn_id) REFERENCES pharmacy_goods_receipt_notes(id);


--
-- Name: pharmacy_sales_line_items fkkdbid8x4k8xm325povuiec5q1; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_sales_line_items
    ADD CONSTRAINT fkkdbid8x4k8xm325povuiec5q1 FOREIGN KEY (stock_id) REFERENCES pharmacy_medicine_stocks(id);


--
-- Name: pharmacy_return_to_suppliers fkkiejynrembc3fqlme0wwgnhsa; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_return_to_suppliers
    ADD CONSTRAINT fkkiejynrembc3fqlme0wwgnhsa FOREIGN KEY (grn_id) REFERENCES pharmacy_goods_receipt_notes(id);


--
-- Name: pharmacy_insurance_claims fkkj2p6f6vq48im5osj6qhluep5; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_insurance_claims
    ADD CONSTRAINT fkkj2p6f6vq48im5osj6qhluep5 FOREIGN KEY (patient_id) REFERENCES pharmacy_patients(id);


--
-- Name: pharmacy_po_line_items fkkp32jyjq2q72rx01418k3odee; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_po_line_items
    ADD CONSTRAINT fkkp32jyjq2q72rx01418k3odee FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_supplier_invoices fkla26r598nw8bq2wkbugo099cb; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_supplier_invoices
    ADD CONSTRAINT fkla26r598nw8bq2wkbugo099cb FOREIGN KEY (supplier_id) REFERENCES pharmacy_suppliers(id);


--
-- Name: pharmacy_medicines fklfb4tbc24ky1c92qlssri0h2; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_medicines
    ADD CONSTRAINT fklfb4tbc24ky1c92qlssri0h2 FOREIGN KEY (supplier_id) REFERENCES pharmacy_suppliers(id);


--
-- Name: pharmacy_activity_logs fkll8rmoblmqfifhs54o387rmmj; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_activity_logs
    ADD CONSTRAINT fkll8rmoblmqfifhs54o387rmmj FOREIGN KEY (user_id) REFERENCES pharmacy_users(id);


--
-- Name: pharmacy_po_line_items fklq0v3c39dbrlliho41gjr2ydr; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_po_line_items
    ADD CONSTRAINT fklq0v3c39dbrlliho41gjr2ydr FOREIGN KEY (po_id) REFERENCES pharmacy_purchase_orders(po_id);


--
-- Name: pharmacy_drug_interactions fknhr8b3y9w1jmyr6o1jhovdnt4; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_drug_interactions
    ADD CONSTRAINT fknhr8b3y9w1jmyr6o1jhovdnt4 FOREIGN KEY (medicine_a_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_stock_batches fknla5nvsv2xnghk3d5t8y9r098; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_stock_batches
    ADD CONSTRAINT fknla5nvsv2xnghk3d5t8y9r098 FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_goods_receipt_notes fkp8nbvy33dyhvbdclcbagvx32l; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_goods_receipt_notes
    ADD CONSTRAINT fkp8nbvy33dyhvbdclcbagvx32l FOREIGN KEY (supplier_id) REFERENCES pharmacy_suppliers(id);


--
-- Name: pharmacy_stock_adjustments fkpb84ghur9p7mnmjgna3u2ia6; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_stock_adjustments
    ADD CONSTRAINT fkpb84ghur9p7mnmjgna3u2ia6 FOREIGN KEY (adjusted_by_user_id) REFERENCES pharmacy_users(id);


--
-- Name: pharmacy_sales_line_items fkpxkufiginetwhfrjo8iqt1s4o; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_sales_line_items
    ADD CONSTRAINT fkpxkufiginetwhfrjo8iqt1s4o FOREIGN KEY (bill_id) REFERENCES pharmacy_sales_bills(id);


--
-- Name: pharmacy_drug_interaction_checks fkq56qfkv3y9drmprdqjin5eh4x; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_drug_interaction_checks
    ADD CONSTRAINT fkq56qfkv3y9drmprdqjin5eh4x FOREIGN KEY (medicine_a_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_stock_alerts fkr2xv8wu02qa7wohu3wws4gc91; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_stock_alerts
    ADD CONSTRAINT fkr2xv8wu02qa7wohu3wws4gc91 FOREIGN KEY (medicine_id) REFERENCES pharmacy_medicines(id);


--
-- Name: pharmacy_stock_batches fkr4e8knuxf5j2qcg8qmpwdd51p; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_stock_batches
    ADD CONSTRAINT fkr4e8knuxf5j2qcg8qmpwdd51p FOREIGN KEY (supplier_id) REFERENCES pharmacy_suppliers(id);


--
-- Name: pharmacy_temperature_logs fkr57rtphm24gyc0r555iuyw614; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_temperature_logs
    ADD CONSTRAINT fkr57rtphm24gyc0r555iuyw614 FOREIGN KEY (unit_id) REFERENCES pharmacy_storage_units(unit_id);


--
-- Name: pharmacy_return_to_suppliers fkr6e1ri2o24wpcwl0georjgl96; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_return_to_suppliers
    ADD CONSTRAINT fkr6e1ri2o24wpcwl0georjgl96 FOREIGN KEY (supplier_id) REFERENCES pharmacy_suppliers(id);


--
-- Name: pharmacy_sales_bills fkrhbrpwcwqfi2ls8ju90hwi2hy; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_sales_bills
    ADD CONSTRAINT fkrhbrpwcwqfi2ls8ju90hwi2hy FOREIGN KEY (doctor_id) REFERENCES pharmacy_doctors(id);


--
-- Name: pharmacy_purchase_order_items fkrhgb6pstukvjalxcexe6pdtmf; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_purchase_order_items
    ADD CONSTRAINT fkrhgb6pstukvjalxcexe6pdtmf FOREIGN KEY (purchase_order_id) REFERENCES pharmacy_purchase_orders(po_id);


--
-- Name: pharmacy_goods_receipt_notes fkruv49uvkclpxrsowk89nvr76c; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_goods_receipt_notes
    ADD CONSTRAINT fkruv49uvkclpxrsowk89nvr76c FOREIGN KEY (purchase_order_id) REFERENCES pharmacy_purchase_orders(po_id);


--
-- Name: pharmacy_insurance_medicine_coverage fks2tx4i52krlsrf9s8yfipt6k9; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_insurance_medicine_coverage
    ADD CONSTRAINT fks2tx4i52krlsrf9s8yfipt6k9 FOREIGN KEY (provider_id) REFERENCES pharmacy_insurance_providers(provider_id);


--
-- Name: pharmacy_supplier_invoices fkstf0ibq7q891rtnd1fxp3evvn; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_supplier_invoices
    ADD CONSTRAINT fkstf0ibq7q891rtnd1fxp3evvn FOREIGN KEY (grn_id) REFERENCES pharmacy_goods_receipt_notes(id);


--
-- Name: pharmacy_return_to_supplier_items fkt55vcjdwv9d41kwragyfhh8d4; Type: FK CONSTRAINT; Schema: public; Owner: clinic_admin
--

ALTER TABLE pharmacy_return_to_supplier_items
    ADD CONSTRAINT fkt55vcjdwv9d41kwragyfhh8d4 FOREIGN KEY (return_id) REFERENCES pharmacy_return_to_suppliers(id);


--
-- PostgreSQL database dump complete
--


